server:
  port: 8092

spring:
  application:
    name: fraud
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: rootpassword
      database: fraud
      port: 27017
      host: localhost
